GET http://localhost:3000/

### SHOW ALL EVENT
GET http://localhost:3000/api/event

### SHOW EVENT BY ID
GET http://localhost:3000/api/event/623c4b93da5ac65e57ee0943

### CREATE NEW EVENT
POST http://localhost:3000/api/event
Content-Type: application/json

{
    "name": "MOTO GP",
    "price": 500000,
    "show_date": "03/24/2022"
}

### UPDATE EVENT BY ID
PATCH  http://localhost:3000/api/event/623c4b93da5ac65e57ee0943
Content-Type: application/json

{
    "name": "MOTO GP INDONESIA",
    "count": 15
}

### REMOVE EVENT BY ID
DELETE  http://localhost:3000/api/event/623bcc0fbf4f614c320973f0